#!/usr/bin/env bash

xscreensaver -no-splash &

# to restore the last wallpaper used in nitrogen
nitrogen --restore &

# change the mouse to standard left-pointing
xsetroot -cursor_name left_ptr &

#exec monsterwm

# from c00kiemonster
# https://bbs.archlinux.org/viewtopic.php?id=126463&p=13

ff="/tmp/monsterwm.fifo"
[[ -p $ff ]] || mkfifo -m 600 "$ff"

ds=("one" "two" "three" "four")

ms=("T" "M" "B" "G" "F")

while read -t 60 -r wmout || true; do
    if [[ $wmout =~ ^(([[:digit:]]+:)+[[:digit:]]+ ?)+$ ]]; then
        unset r
        read -ra desktops <<< "$wmout"
        for desktop in "${desktops[@]}"; do
            IFS=':' read -r d w m c u <<< "$desktop"
            ((c)) && fg="&3" i="${ms[$m]}" || fg="&2"
            ((u)) && w+='&9!'
            r+="$fg${ds[$d]} ${w/#0/&8-}    "
        done
        r="${r%::*}"
        printf "%s\n" "$r &3$i"
    fi

done < "$ff" | splitter_bar &

conky -c ~/.config/conky/conky_monsterwm| while read -r; do xsetroot -name "$REPLY"; done &

monsterwm > "$ff"

rm $ff
